# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cospa_para <- function(X, Y, C, nrank, smin, smax, alpha = 1, tol = 1e-4, max_iter = 200L, verbose = FALSE) {
    .Call('_cospa_cospa_para', PACKAGE = 'cospa', X, Y, C, nrank, smin, smax, alpha, tol, max_iter, verbose)
}

